services:
  pacs:
    image: orthancteam/orthanc:24.10.3
    volumes:
      - ./config/pacs.json:/etc/orthanc/orthanc.json:ro
    ports: ["8101:8042"]
  worker:
    image: orthancteam/orthanc:24.10.3
    volumes:
      - ./config/worker.json:/etc/orthanc/orthanc.json:ro
    ports: ["8103:8042"]
  proxy:
    build:
      context: ..
      dockerfile: staging/Dockerfile
    volumes:
      - ./config/proxy.json:/etc/orthanc/orthanc.json:ro
    ports: ["8102:8042", "4242:4242"]
    depends_on: [pacs, worker]
